[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageAxes = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalOptimisation = "c7c68f13-a4a2-5b9a-b424-07d005f8d9d2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
NRRD = "9bb6cfbd-7763-5393-b1b5-1c8e09872146"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[compat]
AxisArrays = "0.4"
BenchmarkTools = "1"
GenericLinearAlgebra = "0.2"
IJulia = "1"
IntervalArithmetic = "0.19"
IntervalOptimisation = "0.4"
LoopVectorization = "0.12"
MappedArrays = "0.3, 0.4"
OffsetArrays = "1"
ParameterizedFunctions = "5"
Plots = "1"
TestImages = "1"
